
$domein=(Get-ADDomain).DistinguishedName

New-ADOrganizationalUnit -name "Acme" -path "$domein"
New-ADOrganizationalUnit -name "Users" -path "OU=Acme,$domein"

New-ADUser -name "Morgan Freeman" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Morgan.Freeman" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Paz Vega" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Paz.Vega" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Heath Ledger" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Heath.Ledger" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Julia Stiles" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Julia.Stiles" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Joseph Gordon-Levitt" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Joseph.Gordon-Levitt" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Larisa Oleynik" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Larisa.Oleynik" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "David Krumholtz" -Path "OU=Users,OU=Acme,$domein" -samAccountName "David.Krumholtz" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Andrew Keegan" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Andrew.Keegan" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Susan May Pratt" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Susan.May.Pratt" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Gabrielle Union" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Gabrielle.Union" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Larry Miller" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Larry.Miller" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Daryl Mitchell" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Daryl.Mitchell" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Allison Janney" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Allison.Janney" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "David Leisure" -Path "OU=Users,OU=Acme,$domein" -samAccountName "David.Leisure" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Greg Jackson" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Greg.Jackson" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Kyle Cease" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Kyle.Cease" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Terence Heuston" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Terence.Heuston" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Tony Shalhoub" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Tony.Shalhoub" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Embeth Davidtz" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Embeth.Davidtz" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Matthew Lillard" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Matthew.Lillard" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Shannon Elizabeth" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Shannon.Elizabeth" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Alec Roberts" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Alec.Roberts" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "JR Bourne" -Path "OU=Users,OU=Acme,$domein" -samAccountName "JR.Bourne" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Rah Digga" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Rah.Digga" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "F. Murray Abraham" -Path "OU=Users,OU=Acme,$domein" -samAccountName "F..Murray.Abraham" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Matthew Harrison" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Matthew.Harrison" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Jacob Rupp" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Jacob.Rupp" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Daniel Wesley" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Daniel.Wesley" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "John Cusack" -Path "OU=Users,OU=Acme,$domein" -samAccountName "John.Cusack" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Amanda Peet" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Amanda.Peet" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Chiwetel Ejiofor" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Chiwetel.Ejiofor" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Thandie Newton" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Thandie.Newton" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Oliver Platt" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Oliver.Platt" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Thomas McCarthy" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Thomas.McCarthy" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Woody Harrelson" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Woody.Harrelson" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Danny Glover" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Danny.Glover" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Liam James" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Liam.James" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Morgan Lily" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Morgan.Lily" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Zlatko Buric" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Zlatko.Buric" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Beatrice Rosen" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Beatrice.Rosen" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Alexandre Haussmann" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Alexandre.Haussmann" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Philippe Haussmann" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Philippe.Haussmann" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Johann Urb" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Johann.Urb" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Jim Sturgess" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Jim.Sturgess" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Kevin Spacey" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Kevin.Spacey" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Kate Bosworth" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Kate.Bosworth" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Aaron Yoo" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Aaron.Yoo" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Liza Lapira" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Liza.Lapira" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Jacob Pitts" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Jacob.Pitts" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Jack McGee" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Jack.McGee" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Josh Gad" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Josh.Gad" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Helen Carey" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Helen.Carey" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Jack Gilpin" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Jack.Gilpin" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Donna Lows" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Donna.Lows" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Butch Williams" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Butch.Williams" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Ben Campbell" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Ben.Campbell" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Robert Carlyle" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Robert.Carlyle" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Catherine McCormack" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Catherine.McCormack" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Rose Byrne" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Rose.Byrne" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Jeremy Renner" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Jeremy.Renner" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Harold Perrineau" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Harold.Perrineau" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Idris Elba" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Idris.Elba" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Imogen Poots" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Imogen.Poots" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Mackintosh Muggleton" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Mackintosh.Muggleton" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Amanda Walker" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Amanda.Walker" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Emily Beecham" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Emily.Beecham" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Beans El-Balawi" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Beans.El-Balawi" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Gerard Butler" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Gerard.Butler" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Lena Headey" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Lena.Headey" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Dominic West" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Dominic.West" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "David Wenham" -Path "OU=Users,OU=Acme,$domein" -samAccountName "David.Wenham" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Vincent Regan" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Vincent.Regan" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Michael Fassbender" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Michael.Fassbender" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Tom Wisdom" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Tom.Wisdom" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Andrew Pleavin" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Andrew.Pleavin" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Andrew Tiernan" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Andrew.Tiernan" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Rodrigo Santoro" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Rodrigo.Santoro" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Giovani Cimmino" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Giovani.Cimmino" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Stephen McHattie" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Stephen.McHattie" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Greg Kramer" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Greg.Kramer" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Steven Strait" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Steven.Strait" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Camilla Belle" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Camilla.Belle" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Cliff Curtis" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Cliff.Curtis" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Joel Virgel" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Joel.Virgel" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Affif Ben Badra" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Affif.Ben.Badra" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Nathanael Baring" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Nathanael.Baring" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Mona Hammond" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Mona.Hammond" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Reece Ritchie" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Reece.Ritchie" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Joel Fry" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Joel.Fry" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Omar Sharif" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Omar.Sharif" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Armand Assante" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Armand.Assante" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Sigourney Weaver" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Sigourney.Weaver" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Loren Dean" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Loren.Dean" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Michael Wincott" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Michael.Wincott" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Kevin Dunn" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Kevin.Dunn" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Mark Margolis" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Mark.Margolis" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Kario Salem" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Kario.Salem" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "Billy L. Sullivan" -Path "OU=Users,OU=Acme,$domein" -samAccountName "Billy.L..Sullivan" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "John Heffernan" -Path "OU=Users,OU=Acme,$domein" -samAccountName "John.Heffernan" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
New-ADUser -name "John Hurt" -Path "OU=Users,OU=Acme,$domein" -samAccountName "John.Hurt" -AccountPassword (ConvertTo-securestring -Force -AsPlainText "R1234-56") -PasswordNeverExpires $true -Enabled $true
